//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AStar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StepsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StepsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AStar.Resources.StepsResource", typeof(StepsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 - Initializing..
        /// </summary>
        internal static string StepInfo0 {
            get {
                return ResourceManager.GetString("StepInfo0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Adding start node to OPEN.
        /// </summary>
        internal static string StepInfo1 {
            get {
                return ResourceManager.GetString("StepInfo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.d.i - Found! Target is on CLOSE..
        /// </summary>
        internal static string StepInfo10 {
            get {
                return ResourceManager.GetString("StepInfo10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.d.ii - Not found! OPEN is empty..
        /// </summary>
        internal static string StepInfo11 {
            get {
                return ResourceManager.GetString("StepInfo11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Generate path using the node&apos;s PARENTs..
        /// </summary>
        internal static string StepInfo12 {
            get {
                return ResourceManager.GetString("StepInfo12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Repeat:.
        /// </summary>
        internal static string StepInfo2 {
            get {
                return ResourceManager.GetString("StepInfo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.a - Search node with lowest F cost on OPEN. This is the CURRENT node..
        /// </summary>
        internal static string StepInfo3 {
            get {
                return ResourceManager.GetString("StepInfo3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.b - Move this node to the CLOSE list..
        /// </summary>
        internal static string StepInfo4 {
            get {
                return ResourceManager.GetString("StepInfo4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.c - Repeat for each neighbour:.
        /// </summary>
        internal static string StepInfo5 {
            get {
                return ResourceManager.GetString("StepInfo5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.c.i - Ignore if it&apos;s an obstacle or on CLOSE..
        /// </summary>
        internal static string StepInfo6 {
            get {
                return ResourceManager.GetString("StepInfo6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.c.ii - If it&apos;s not on OPEN, add to OPEN and change the node&apos;s parent to CURRENT. Save f, g and h..
        /// </summary>
        internal static string StepInfo7 {
            get {
                return ResourceManager.GetString("StepInfo7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.c.iii - If it&apos;s already on OPEN, check if the new g value is lower than the previous. If it is, change PARENT, f, g and h to new values..
        /// </summary>
        internal static string StepInfo8 {
            get {
                return ResourceManager.GetString("StepInfo8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.d - Stop processing when:.
        /// </summary>
        internal static string StepInfo9 {
            get {
                return ResourceManager.GetString("StepInfo9", resourceCulture);
            }
        }
    }
}
